### ISSUE TITLE
How to change Confirm URL & Cancel URL runtime !

### ISSUE THREAD

**Issue by nishant-befree** [stdevteam/yii-paypal#9]
Confirm & cancel URL setting inside config file.

i want to change it as per my requirement when i doing checkout,

can anyone tell me how it possible with this extension?

**Comment by abudulwadoodu** [comment]
Hi,

Here is how I changed the url.
POST a form with url/details to 'paypalController/buy'. In top of that function, i wrote

    $paypalObj = Yii::app()->Paypal;
    
    $paypalObj->returnUrl= 'my new confirm url';
    $paypalObj->cancelUrl= 'my new cancel url';

// no other changes, just added the above lines
Thanks,
Abdul Wadood.
